### PR TITLE
added DeploymentItemExAttribute, much like DeploymentItem, but supports long file paths

### PR DESCRIPTION
**Pull request by icnocop**
Notice there are two "// TODO:" items.
1. The ability to output warnings to the test results log file.

Is this possible?
1. The ability to get the value of the RelativePathRoot property setting in the current .testsettings file

See this msdn article for more information:
http://msdn.microsoft.com/en-us/library/ms182475%28v=vs.100%29.aspx
"Relative paths are relative to the RelativePathRoot setting found in the .testrunconfig file."

I could not personally find this specific setting, so I'm not sure if this is just a documentation error.  I've also read that it is set to the solution directory by default, so that is what I am trying to use for now.

Once this new attribute looks good, I can go ahead and try to add unit\integration tests for it.

What do you think?

Thank you.

### CODE REVIEW

**Comment by icnocop** [comment]
See related discussion: http://mstestextensions.codeplex.com/discussions/437712

**Comment by CallumHibbert** [comment]
What does this give us over using the ".testsettings" and adding items under the "Deployment" section?

Also, I not personally had any issues with the built in "DeploymentItem" attribute, I'm not saying there aren't any issues with it but I wondered what problem we are solving with this new attribute.

Thanks.

**Comment by icnocop** [comment]
The DeploymentItem attribute allows us to specify the deployment items that are only specific to each test for example.  In this way, the external resources are coupled with the tests that require them which makes it easier to manage in the scenarios where tests are changed or removed, the deployment items are as close to the tests that use them as possible.  The DeploymentItem can be used on both test classes and methods.

As noted in DeploymentItemExAttribute.cs:
DeploymentItemEx, much like DeploymentItem, but supports long file paths.

DeploymentItemEx allows source and destination deployment items to have long file paths (greater than 256 characters).

I remember creating a Microsoft connect bug on the issue but I can't find it anymore because they archived a lot of their "old" bug reports.  I remember that the issue was marked as Closed with either "Won't Fix" or "By Design", etc.

**Comment by icnocop** [comment]
I actually found the Microsoft connect bug here:
http://connect.microsoft.com/VisualStudio/feedback/details/753341/unit-test-deploymentitem-attribute-is-limits-file-paths-with-a-maximum-file-path-length-of-about-256-characters

**Comment by CallumHibbert** [comment]
OK, sounds good. Please can you do two things:

1 - Rename "DeploymentItemExAttribute" to "DeploymentItemWithLongPathAttribute" as that's a more descriptive name.

2 - We are introducing a dependency on "ZetaLongPaths", so can you please add that as a dependent package in the NuGet package definition at "Source\Artefacts\NuGet\StealFocus.MSTestExtensions\StealFocus.MSTestExtensions.nuspec".

e.g.

```
<dependencies>
  <dependency id="ZetaLongPaths" version="1.0.0" />
</dependencies>
```

Once this is done, I'll merge your changes and push a new build to NuGet.

Thanks.

**Comment by icnocop** [comment]
Hi Callum,

Not sure if you got notified on the last commit, but just wanted to let you know that I've added a commit to resolve the issues you addressed.

Thank you.

**Comment by CallumHibbert** [comment]
Rami,

No, I don't get notified of the updated pull request. Have merged your
changes just now and there is a new version on NuGet.

If you get the chance, it would be great to have a unit test for this.

Thanks.

**Pull request merged**
